# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    name: ament_lint
    runs-on: ubuntu-20.04
    strategy:
      matrix:
          linter: [xmllint, lint_cmake, copyright]
    steps:
      - uses: actions/checkout@v2
      - uses: ros-tooling/setup-ros@0.1.1
      - uses: ros-tooling/action-ros-lint@master
        with:
          distribution: melodic
          linter: ${{ matrix.linter }}
          package-name:
            removert
