# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    name: build
    runs-on: ubuntu-20.04
    steps:
      - name: setup directories
        run: mkdir -p removert_ws/src
      - name: checkout
        uses: actions/checkout@v2
        with:
          path: removert_ws/src
      - uses: ros-tooling/setup-ros@0.0.25
        with:
          required-ros-distributions: melodic
      - uses: ros-tooling/action-ros-ci@0.0.19
        with:
          package-name: removert
          target-ros1-distro: melodic
          vcs-repo-file-url: ""
