# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  ament_lint:
    name: ament_lint
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: ros-tooling/setup-ros@v0.1
        with:
          required-ros-distributions: melodic
      - uses: ros-tooling/action-ros-ci@v0.1
        with:
          package-name: removert
          target-ros1-distro: melodic
          vcs-repo-file-url: ""
